### ISSUE TITLE
How to choose the right cube sizes?

### ISSUE THREAD

**Issue by diealecel** [moberweger/deep-prior-pp#26]
Hi, I hope you're having a great day. Thank you for the amazing work!

I'm trying to train DeepPrior++ on my own dataset and I'm currently having issues, which I've managed to narrow down to the camera intrinsics numbers and the cube size numbers set in `importers.py`. I've also noticed that for some datasets the cube sizes change depending on what part of the dataset is being looked at. How do I choose a cube size that will work with my dataset?

Thank you for the help!

**Comment by moberweger** [comment]
Hi @diealecel 
The cube size depends on the physical hand size of the user. In order to work better, the cube size should cover the full hand when using a flat frontal hand pose. You can empirically adjust the cube size such that it fits the hand plus some margin.
There is also a calibration procedure in the realtimepipeline, but this is not perfectly tuned.
