### ISSUE TITLE
Scale augmentation

### ISSUE THREAD

**Issue by LuciaXu** [moberweger/deep-prior-pp#3]
Hi, @moberweger

Thanks for sharing your work.
After reading your great paper and the code, I have a question about the scaling augmentation. In the paper,  you said that "we scale the 3D joint locations according to the random factor". However, I failed to find it in the scaleHand function. It seems that you just made the new_joints3D equal to the joints3D. 
Did I missed something here?

**Comment by moberweger** [comment]
HI,
Yes, you are right that in HandDetector:scaleHand we only scale the image not the joint locations, since the joint locations are in (unnormalized) 3D coordinates, but we scale the crop cube. The scaling of the joint locations is done in NetTrainer:augmentCrop, where the joint locations get normalized by the crop cube, which was adjusted in scaleHand.

**Comment by LuciaXu** [comment]
Thanks very much! @moberweger
